### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by on3iro** [on3iro/vally#1]
* [ ] Remove babel-polyfill (add object-spread if necessary)
* [x] enhance lib
    * [x] refactor code
    * [x] increase coverage
    * [x] add imports/exports to index.js
    * [x] add docstrings 
* [x] releases
    * [x] beta release for testing purposes
    * [x] initial release
* [x] repo
    * [x] set up CI (travis, coveralls, codeclimate)
    * [x] documentation
    * [x] importable libdefs
